#!/usr/bin/python3

# -*- coding:utf-8 -*-
from PIL import Image, ImageDraw, ImageFont  # Font handeling
from waveshare_epd import epd2in13_V2
import os
from ser2bt_lib import line_pos, center_text
#user-changable settings.
screen_rotate = 180
foreground = 0
background = 255

# Variable decleration
epd = epd2in13_V2.EPD()
tmp_dir = "/tmp/"
shut_file = "shut"
title_msg = 'Loading:'
msg = 'Serial to bluetooth bridge'
np = True #New Page, True or False
roboto_font_dir='/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/'
f_title_font18 = ImageFont.truetype(roboto_font_dir+'Roboto-Bold.ttf', 18)
f_title_font24 = ImageFont.truetype(roboto_font_dir+'Roboto-Bold.ttf', 24)

#Check if battery file exists, create if it does not:
if not os.path.exists(tmp_dir+shut_file):
    os.mknod(tmp_dir+shut_file)

#Then, change the rights on the file.
os.chmod(tmp_dir+shut_file, 0o664)

#Clear the Screen:
epd.init(epd.FULL_UPDATE)
epd.Clear(background)

#Draw out the boot screen
boot_image = Image.new('1', (epd.height, epd.width), background)  #clear the frame
boot_draw = ImageDraw.Draw(boot_image)

#Plot the text:
boot_draw.text((center_text(boot_draw, title_msg, f_title_font24), line_pos(np,boot_draw, title_msg, f_title_font24)), title_msg, font=f_title_font24, fill = foreground)
np = False
boot_draw.text((center_text(boot_draw, msg, f_title_font18), line_pos(np,boot_draw, msg, f_title_font18)), msg, font=f_title_font18, fill = foreground)

#Display the screen
epd.display(epd.getbuffer(boot_image.rotate(screen_rotate)))

#Exit:
epd2in13_V2.epdconfig.module_exit()
exit()