#!/bin/bash

#color and other formatting defenitions:
source /usr/local/lib/format.sh

#Location settings:
home="/home/${SUDO_USER}/"
project_folder="${home}/Projects/ser2bt-bridge/"
support_folder="${home}/Projects/support/"
logging_folder="${home}/console_logs/"
bin_folder="/usr/local/bin/"
lib_folder="/usr/local/lib/"
etc_folder="/etc/"
service_folder="/etc/systemd/system/"

#File list:
base_bin_files=(ser2bt_bridge)
enhanc_bin_files=(ser2bt_status init_scr shutdown_scr)
full_bin_files=( "${base_bin_files[@]}" "${enhanc_bin_files[@]}" )
base_lib_files=(format.sh)
enhanc_lib_files=(logo.bmp)
full_lib_files=( "${base_lib_files[@]}" "${enhanc_lib_files[@]}" )
etc_files=(ser2bt_bridge.screenrc)
base_service_files=(rfcomm.service)
enhanc_service_files=(ser2bt-e-paper.service ser2bt-e-paper-init.service ser2bt-e-paper-shut.service)
full_service_files=( "${base_service_files[@]}" "${enhanc_service_files[@]}" )
enhanc_service_assoc=(ser2bt_status ser2bt-e-paper.service)
full_service_assoc=( "${enhanc_service_assoc[@]}" )
begin_bashrc_addon_mark="#BEGIN ser2b-bridge .bashrc add-in"
end_bashrc_addon_mark="#END ser2b-bridge .bashrc add-in"
bin_flag=0

#printf "${full_service_assoc[0]}\n"
#exit 0
#Checks before begining:
# Make sure the script is run with superuser privelages
if [[ "${UID}" -ne 0 ]]; then
	printf "\n${nor}You do ${drk_red}not ${nor}have the permissions to successfully run this script.\n"
	exit 1
fi

#check for minimum arguements:
if [[ "${#}" -lt 1 ]]; then
	echo "Usage: ${0} UPGRADE_PATH [BASIC|ENHANCED|FULL]."
	echo "Upgrade ser2bt-bridge, and choose either basic, enhanced, or full."
	exit 2
fi

if [ "${upgrade_path}" = "basic" ] ; then
	bin_files=( "${base_bin_files[@]}" )
	lib_files=( "${base_lib_files[@]}" )
	service_files=( "${base_service_files[@]}" )
fi

if [ "${upgrade_path}" = "enhanced" ] ; then
	bin_files=(${enhanc_bin_files[@]})
	lib_files=(${enhanc_lib_files[@]})
	service_files=(${enhanc_service_files[@]})
	service_assoc=(${enhanc_service_assoc[@]})
fi

if [ "${upgrade_path}" = "full" ] ; then
	bin_files=(${full_bin_files[@]})
	lib_files=(${full_lib_files[@]})
	service_files=(${full_service_files[@]})
	service_assoc=(${full_service_assoc[@]})
fi

#assign the upgrade path to the first argument
upgrade_path="${1}"
shift

#Starting script here:
printf "\n\n${nor}Beginning ${upgrade_path} upgrade of ${yel}ser2bt-bridge${nor}:\n\n"

#Upgrade system files
#printf "\r${nor}Update package manager:\n"
#apt update > /dev/null 2>&1
#if [ ${?} -gt 0 ]; then
#	printf "${red}Update failed, exiting to shell\n"
#	exit 1 #apt update or apt full-upgrade failed"
#fi
#apt full-upgrade -y > /dev/null 2>&1
#if [ ${?} -gt 0 ]; then
#	printf "${red}Upgrade failed, exiting to shell\n"
#	exit 1 #apt update or apt full-upgrade failed"
#fi

#make directorys:
	printf "${nor}Check to make sure the ${cyn}${support_folder} ${nor}directories exist:\n"
	if [ ! -d ${support_folder} ]; then
		printf " ${nor}Directory does ${drk_red}not ${nor}exist, creating...\n"
		mkdir -p ${support_folder}
	else
		printf " ${nor}Directory ${drk_grn}already ${nor}exist, moving on.\n"
	fi

	printf "\n${nor}check to make sure the ${cyn}${logging_folder} ${nor}directories exist:\n"
	if [ ! -d ${logging_folder} ]; then
		printf " ${nor}Directory does ${drk_red}not ${nor}exist, creating...\n"
		mkdir -p ${logging_folder}
	else
		printf " ${nor}Directory ${drk_grn}already ${nor}exist, moving on.\n"
	fi

	#copy files to proper directories:
	printf "\nCopying files to the ${cyn}${bin_folder} ${nor}directory:\n"
	for file in ${bin_files[@]} ; do
#		printf "${service_assoc[1]}\n"
		if cmp --silent "${bin_folder}${file}" "${project_folder}${file}" ; then
			printf " ${nor}Both versions of ${yel}${file} ${nor}are the same, Skipping...\n"
		else
			if [ "${file}" == "${service_assoc[0]}" ] ; then
				bin_flag=1
			fi
			cp ${project_folder}${file} ${bin_folder} && printf " ${yel}${file} ${nor}copied.\n" || break
		fi
	done

	printf "\nCopying files to the ${cyn}${lib_folder} ${nor}directory:\n"
	for file in ${lib_files[@]} ; do
		if cmp --silent "${lib_folder}${file}" "${project_folder}${file}" ; then
			printf " ${nor}Both versions of ${yel}${file} ${nor}are the same, Skipping...\n"
		else
			cp ${project_folder}${file} ${lib_folder} && printf " ${yel}${file} ${nor}copied.\n" || break
		fi
	done

	printf "\nCopying files to the ${cyn}${etc_folder} ${nor}directory:\n"
	for file in ${etc_files[@]} ; do
		if cmp --silent "${etc_folder}${file}" "${project_folder}${file}" ; then
			printf " ${nor}Both versions of ${yel}${file} ${nor}are the same, Skipping...\n"
		else
			cp ${project_folder}${file} ${etc_folder} && printf " ${yel}${file} ${nor}copied.\n" || break
		fi
	done

	printf "\nCopy service files to the ${cyn}${service_folder} ${nor}directory, then disable and enable copied services:\n"
	svc_count=0
#	printf "service count:${service_files[2]}\n"
	for svc_file in ${service_files[@]} ; do
		if cmp --silent "${service_folder}${svc_file}" "${project_folder}${svc_file}" ; then
			printf " ${nor}Both versions of ${yel}${svc_file} ${nor}are the same, Skipping...\n"
			let svc_count++
		else
			cp ${project_folder}${svc_file} ${service_folder} && printf " ${yel}${svc_file} ${nor}copied.\n" || break
			systemctl disable ${svc_file} && printf " ${nor}${svc_file} ${drk_grn}successfully ${nor}disabeled.\n" || break
			systemctl enable ${svc_file} && printf " ${nor}${svc_file} ${drk_grn}successfully ${nor}enabeled.\n" || break
		fi
	done

	if [[ "${bin_flag}" -gt 0 ]] ; then
		printf "\n${nor}Restarting ${service_assoc[1]} (as needed):${nor}\n"
		systemctl restart "${service_assoc[1]}" && printf " ${nor}e-paper service ${drk_grn}Successfully ${nor}Restarted.\n" || printf "${drk_red}Failed ${yellow}${svc_file}${nor}!\n"
	fi

	if [ ${svc_count} != ${#service_files[@]} ] || [[ "${bin_flag}" -gt 0 ]] ; then
		printf "\n${nor}Restarting systemctl (as needed):${nor}\n"
		systemctl daemon-reload && printf " ${yel}systemctl daemon-reload${nor} was ${drk_grn}Successfull${nor}.\n" || printf " ${nor}systemctl daemon-reload was ${drk_red}not ${nor}successfull.\n"
	fi

#refreshing .bashrc:
printf "\nAdding the ${yel}.bashrc${nor} addon (if it's already on, it will be removed and replaced):\n"
#First compare whats in bashrc matches the addendum:
existing_ver=$(awk '/^#BEGIN/,/^#END/ { print }' ${home}.bashrc)
official_ver=$(awk '/^#BEGIN/,/^#END/ { print }' ${project_folder}bashrc_addendum.sh)
if [ "${existing_ver}" != "${official_ver}" ] ; then
	printf " ${nor}There is a difference between what is supposed to be in ${yel}.bashrc${nor}, will clean and re-apply ${yel}ser2bt-bridge${nor} related configurations:\n" 
	sed -i '/^#BEGIN ser2b-bridge .bashrc add-in/, /^#END ser2b-bridge .bashrc add-in/d' ${home}.bashrc
	cat bashrc_addendum.sh >> ${home}.bashrc && printf " ${drk_grn}Done${nor}.\n" || printf " ${drk_grn}Failed${nor}.\n"
else
	printf " ${nor}Both versions are the same, skipping...\n"
fi
exit 0
