#!/usr/bin/python3

# -*- coding:utf-8 -*-
from PIL import Image, ImageDraw, ImageFont  # Font handeling
from waveshare_epd import epd2in13_V2

import configparser #to handle the config file.

#import configuration file:
#Read ser2bt_config.ini file
config_obj = configparser.ConfigParser()
config_obj.read("/etc/ser2bt_config.ini")
screen = config_obj["screen"]
shutdown_screen = config_obj["shutdown_screen"]

# parameters to use the keys from the ser2bt_config.ini
screen_rotate = int(screen["screen_rotate"])
foreground = int(screen["foreground"])
background = int(screen["background"])

# Variable decleration
epd = epd2in13_V2.EPD()
roboto_font_dir='/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF/'
f_title_font18 = ImageFont.truetype(roboto_font_dir+'Roboto-Bold.ttf', 18)
f_title_font24 = ImageFont.truetype(roboto_font_dir+'Roboto-Medium.ttf', 24)

#Clear the Screen:
epd.init(epd.FULL_UPDATE)
#epd.Clear(background)

#Draw out the boot screen
boot_image = Image.new('1', (epd.height, epd.width), int(background))  #clear the frame
boot_draw = ImageDraw.Draw(boot_image)

#Plot the text:
boot_draw.text((80, 20), 'Standby:', font=f_title_font24, fill = int(foreground))
boot_draw.text((26, 55), 'Serial 2 Bluetooth Bridge', font=f_title_font18, fill = int(foreground))
boot_draw.text((58, 78), 'is being updated!', font=f_title_font18, fill = int(foreground))

#Display the screen
epd.display(epd.getbuffer(boot_image.rotate(screen_rotate)))

#Exit:
epd.sleep()
#epd2in13_V2.epdconfig.module_exit()
exit()